#!/usr/bin/env sh

##############################################################################
##
##  Bazel start up script for UN*X (based on gradlew script from gradle wrapper project)
##
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="bazelisk"
APP_BASE_NAME=`basename "$0"`

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

## Determine OS.
darwin=false
linux=false

case "`uname`" in
  Darwin* )
    darwin=true
    ;;
  Linux* )
    linux=true
    ;;
esac

BINARY_PATH=""
if $darwin; then
    BINARY_PATH=bazelisk-darwin-amd64
elif $linux; then
    BINARY_PATH=bazelisk-linux-amd64
else
   die "UNSUPPORTED OS! Command 'uname' says: `uname`. 'darwin' = $darwin and 'linux' = $linux"
fi


exec "$APP_HOME/bazelisk/$BINARY_PATH" "$@"
